REM Copyright (C) 2013 Jacob Barhak
REM Copyright (C) 2009-2012 The Regents of the University of Michigan
REM 
REM This file is part of the MIcroSimulation Tool (MIST). The MIcroSimulation Tool (MIST) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
REM 
REM The MIcroSimulation Tool (MIST) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. 
REM %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
REM 
REM ADDITIONAL CLARIFICATION
REM 
REM The MIcroSimulation Tool (MIST) is distributed in the hope that it will be useful, but "as is" and WITHOUT ANY WARRANTY of any kind, including any warranty that it will not infringe on any property rights of another party or the IMPLIED WARRANTIES OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS assume no responsibilities with respect to the use of the MIcroSimulation Tool (MIST).
REM 
REM The MIcroSimulation Tool (MIST) was derived from the Indirect Estimation and Simulation Tool (IEST) and uses code distributed under the IEST name. The change of the name signifies a split from the original design that focuses on microsimulation. For the sake of completeness, the copyright statement from the original tool developed by the University of Michigan is provided below and is also mentioned above.
REM 
REM %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
REM %%%%%%%%%%%%%%%%%%%%%%%% Original Copyright %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
REM %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
REM Copyright (c) 2011 The Regents of the University of Michigan. Initially developed by Jacob Barhak
REM This file is part of the Indirect Estimation and Simulation Tool (IEST).  The Indirect Estimation and Simulation Tool (IEST) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
REM 
REM The Indirect Estimation and Simulation Tool (IEST) is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
REM 
REM ADDITIONAL CLARIFICATION
REM 
REM The Indirect Estimation and Simulation Tool (IEST) is distributed in the hope that it will be useful, but "as is" and WITHOUT ANY WARRANTY of any kind, including any warranty that it will not infringe on any property rights of another party or the IMPLIED WARRANTIES OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE UNIVERSITY OF MICHIGAN assumes no responsibilities with respect to the use of the Indirect Estimation and Simulation Tool (IEST).  
REM 
REM This file copies images generated by save as jpg from ImagePreperation.ppt to their correct name and location to be used with the html files generated by DocSrc.texi using TexInfo

copy ImagePreperation\Slide1.JPG Documentation\Images\mainform.jpg
copy ImagePreperation\Slide2.JPG Documentation\Images\states.jpg
copy ImagePreperation\Slide3.JPG Documentation\Images\model.jpg
copy ImagePreperation\Slide4.JPG Documentation\Images\transitionsmodel.jpg
copy ImagePreperation\Slide5.JPG Documentation\Images\populations.jpg
copy ImagePreperation\Slide6.JPG Documentation\Images\popdata.jpg
copy ImagePreperation\Slide7.JPG Documentation\Images\parameter_filter.jpg
copy ImagePreperation\Slide8.JPG Documentation\Images\parameters.jpg
copy ImagePreperation\Slide9.JPG Documentation\Images\simulation.jpg
copy ImagePreperation\Slide10.JPG Documentation\Images\costwizard.jpg
copy ImagePreperation\Slide11.JPG Documentation\Images\resultviewer.jpg
copy ImagePreperation\Slide12.JPG Documentation\Images\reportviewer.jpg
copy ImagePreperation\Slide13.JPG Documentation\Images\reportvieweroptions.jpg
copy ImagePreperation\Slide14.JPG Documentation\Images\copytransitions.jpg
copy ImagePreperation\Slide15.JPG Documentation\Images\modeldiagram.jpg

